# Generated by Django 5.1.1 on 2024-11-21 23:27

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def add_default_entries(apps, schema_editor):
    PrescriptionApp = apps.get_model('prescriptionapp', 'PrescriptionApp')

    PrescriptionApp.objects.create(
        issue_date=timezone.now().date(),
        expiration_date=(timezone.now() + timedelta(days=30)).date(),
        doctor_full_name='Dr. John Doe',
        medication='Ibuprofen',
        dosage='200mg',
        frequency='Twice daily',
        refill_info='3 refills remaining',
        instructions='Take with food'
    )

    PrescriptionApp.objects.create(
        issue_date=timezone.now().date(),
        expiration_date=(timezone.now() + timedelta(days=60)).date(),
        doctor_full_name='Dr. Jane Smith',
        medication='Lisinopril',
        dosage='10mg',
        frequency='Once daily',
        refill_info='5 refills remaining',
        instructions='Take in the morning'
    )

    PrescriptionApp.objects.create(
        issue_date=timezone.now().date(),
        expiration_date=(timezone.now() + timedelta(days=90)).date(),
        doctor_full_name='Dr. Robert Johnson',
        medication='Metformin',
        dosage='500mg',
        frequency='Twice daily',
        refill_info='2 refills remaining',
        instructions='Take before meals'
    )

    PrescriptionApp.objects.create(
        issue_date=timezone.now().date(),
        expiration_date=(timezone.now() + timedelta(days=45)).date(),
        doctor_full_name='Dr. Emily Davis',
        medication='Atorvastatin',
        dosage='10mg',
        frequency='Once daily',
        refill_info='4 refills remaining',
        instructions='Take at bedtime'
    )

    PrescriptionApp.objects.create(
        issue_date=timezone.now().date(),
        expiration_date=(timezone.now() + timedelta(days=120)).date(),
        doctor_full_name='Dr. Michael Wilson',
        medication='Amoxicillin',
        dosage='500mg',
        frequency='Three times daily',
        refill_info='6 refills remaining',
        instructions='Take with food'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('prescriptionapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_entries),
    ]
