# Generated by Django 5.1.1 on 2024-11-22 00:03

from django.db import migrations
from datetime import date, time

def create_dummy_entries(apps, schema_editor):
    UserHeartApp = apps.get_model('userheartapp', 'UserHeartApp')

    UserHeartApp.objects.create(appointment_day=date(2024, 12, 1), appointment_time=time(9, 0), patient_name='John Doe', status='Completed', observations='All tests normal.', heart_rate=72, blood_pressure_systolic=120, blood_pressure_diastolic=80, oxygen_saturation=98.5)
    UserHeartApp.objects.create(appointment_day=date(2024, 12, 2), appointment_time=time(10, 0), patient_name='Jane Doe', status='Pending', observations='Minor irregularities noted.', heart_rate=75, blood_pressure_systolic=130, blood_pressure_diastolic=85, oxygen_saturation=97.8)
    UserHeartApp.objects.create(appointment_day=date(2024, 12, 3), appointment_time=time(11, 0), patient_name='Alice Smith', status='Completed', observations='High blood pressure.', heart_rate=70, blood_pressure_systolic=145, blood_pressure_diastolic=90, oxygen_saturation=99.2)
    UserHeartApp.objects.create(appointment_day=date(2024, 12, 4), appointment_time=time(12, 0), patient_name='Bob Johnson', status='Cancelled', observations='Patient unavailable.', heart_rate=68, blood_pressure_systolic=110, blood_pressure_diastolic=70, oxygen_saturation=98.0)
    UserHeartApp.objects.create(appointment_day=date(2024, 12, 5), appointment_time=time(13, 0), patient_name='Emily Davis', status='Completed', observations='All tests normal.', heart_rate=73, blood_pressure_systolic=125, blood_pressure_diastolic=82, oxygen_saturation=98.7)



class Migration(migrations.Migration):

    dependencies = [
        ('userheartapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_entries),
    ]