# Generated by Django 5.1.1 on 2024-11-22 00:06

from django.db import migrations
from datetime import date, time
from django.utils import timezone

def create_dummy_entries(apps, schema_editor):
    UserMaternityApp = apps.get_model('usermaternityapp', 'UserMaternityApp')

    # Create the first dummy entry
    UserMaternityApp.objects.create(
        appointment_day=timezone.now().date(),
        appointment_time=timezone.now().time(),
        patient_name='Patient 1',
        status='Scheduled',
        observations='This is the first dummy observation.',
        pregnancy_week=1,
    )

    # Create the second dummy entry
    UserMaternityApp.objects.create(
        appointment_day=timezone.now().date(),
        appointment_time=timezone.now().time(),
        patient_name='Patient 2',
        status='Completed',
        observations='This is the second dummy observation.',
        pregnancy_week=2,
    )

    # Create the third dummy entry
    UserMaternityApp.objects.create(
        appointment_day=timezone.now().date(),
        appointment_time=timezone.now().time(),
        patient_name='Patient 3',
        status='Cancelled',
        observations='This is the third dummy observation.',
        pregnancy_week=3,
    )

    # Create the fourth dummy entry
    UserMaternityApp.objects.create(
        appointment_day=timezone.now().date(),
        appointment_time=timezone.now().time(),
        patient_name='Patient 4',
        status='Rescheduled',
        observations='This is the fourth dummy observation.',
        pregnancy_week=4,
    )

    # Create the fifth dummy entry
    UserMaternityApp.objects.create(
        appointment_day=timezone.now().date(),
        appointment_time=timezone.now().time(),
        patient_name='Patient 5',
        status='Scheduled',
        observations='This is the fifth dummy observation.',
        pregnancy_week=5,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('usermaternityapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dummy_entries),
    ]