# Generated by Django 5.1.1 on 2024-11-21 22:00

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionApp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('doctor_full_name', models.CharField(max_length=255)),
                ('medication', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=255)),
                ('refill_info', models.CharField(blank=True, max_length=255, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]