# Generated by Django 5.1.1 on 2024-11-19 09:22

from django.db import migrations

def add_default_entries(apps, schema_editor):
    UserApp = apps.get_model('userapp', 'UserApp')
    UserApp.objects.create(appointment_day='2024-11-19', appointment_time='10:00:00', doctor_name='Dr. Kini', status='Pending', observations='Follow-up appointment')
    UserApp.objects.create(appointment_day='2024-11-21', appointment_time='14:30:00', doctor_name='Dr. Chandan Kamath', status='Confirmed', observations='Routine check-up')
    UserApp.objects.create(appointment_day='2024-12-04', appointment_time='09:00:00', doctor_name='Dr. Prashan Kumar', status='Cancelled', observations='Patient unavailable')

class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_entries),
    ]